### ISSUE TITLE
details.ts-accordion 在嵌套情況下的 ::before icon 問題

### ISSUE THREAD

**Issue by runnywolf** [teacat/tocas#1072]
像是這樣
```html
<details class="ts-accordion">
  <summary>營業時間為何？</summary>
  
  <details class="ts-accordion">
    <summary>營業時間為何？</summary>
    每日的早上九點至晚上八點。
  </details>
</details>
```

當外層 details open，外層的 ::before icon 會轉向為 0deg (開啟狀態)，
這同時會讓內層的 ::before icon 也同時轉為 0deg，即使內層 details 沒有被 open。

由於我目前只使用到雙層嵌套，所以我先這樣解決：
```css
details.ts-accordion[open] details.ts-accordion:not([open]) summary::before {
  transform: rotate(270deg);
}
```

另外，很謝謝你的 css 模板，使用起來非常方便和好看。
