### ISSUE TITLE
[T2] 替 Menu 新增 Fixed Top, Left, Bottom, Right 方案

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#231]
替代 `position: fixed` 還有 `top: 0;` 等⋯⋯。

```css
.ts.top.fixed.menu {
        left: 0px;
        right: 0px;
        width: 100%;
        position: fixed;
        top: 0px;
        z-index: 13;
 }
```
