### ISSUE TITLE
選單的 CSS 會影響到下拉式選單的運作

### ISSUE THREAD

**Issue by gnehs** [teacat/tocas#436]
不取消這條 CSS 的話下拉式選單不能正常運作
```css
.ts.menu[class*="horizontally scrollable"]:not(.secondary):not(.pointing):not(.tabbed) {
    overflow-x: auto;
}
```
![1498463603 0626 1553](https://user-images.githubusercontent.com/16719720/27529831-96a78714-5a88-11e7-8fa5-62733faf7b11.png)
取消前
![1498463610 0626 1553](https://user-images.githubusercontent.com/16719720/27529819-8cd5cb2e-5a88-11e7-8013-5ada5c4d20fe.png)
取消後

Jade
```jade
.ts.basic.link.fluid.top.attached.menu.horizontally.scrollable
    .ts.container
        a.item(href='index.html') Tocas Xiaoan
        .ts.item.dropdown
            .text Xiaoan CSS
            i.dropdown.icon
            .menu
                a.item(href='main-basic.html') 基本
                a.item(href='main-icon-font.html') Icon Font
        a.item(href='main-tocas-example.html') 範例集
        a.item(href='breeding.html') 配種
        a.right.item(href='https://github.com/gnehs/Tocas-UI-Xiaoan/', target='_blank') GitHub
```
