### ISSUE TITLE
允許 Progress 的 Text 在進度條內以 Absolute 的方式浮空置中

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#546]
允許 Progress 裡的 Text 可以浮在空中並永遠置中，避免 Bar 太短無法顯示文字。

同時加上這個功能後，Text 也不需要一直跟著 Bar 的最前端跑。

![2017-12-11 2 57 34](https://user-images.githubusercontent.com/7308718/33808343-a1430052-de1f-11e7-9165-c42a0adccc11.png)

```css
{
    position: absolute;
    top: 50%;
    z-index: 20;
    left: 0;
    left: 50%;
    transform: translateX(-50%) translateY(-50%);
    color: #FFF;
}
```
