### ISSUE TITLE
iOS 下的慣性滾動失效

### ISSUE THREAD

**Issue by MiliChang** [teacat/tocas#570]
iOS 11 Safari
在滑動頁面時由於沒有慣性滾動，滑起來感覺很笨重......

**Comment by YamiOdymel** [comment]
這個問題可能不是由 Tocas UI 所導致的，因為我在 Macbook 上用軌跡版滾動沒有什麼問題。

有更詳細的說明是在哪個頁面發生的嗎？或是一些更詳細的情況？

---

如果遇到這個狀況，使用 [StackOverflow](https://stackoverflow.com/questions/18998365/ios-safari-vertical-scrolling-feels-sticky-with-no-momentum) 提到的做法看能否改善。

```css
* {
  -webkit-overflow-scrolling: touch;
}
```
