### ISSUE TITLE
.ts.inverted.dropdown items color

### ISSUE THREAD

**Issue by toby3d** [teacat/tocas#580]
Tocas not supported inverted colors for `.dropdown .item` elements. Yet.
```html
<nav class="ts top fixed borderless inverted menu">
  <div class="ts text container">
    ...
    <div class="right menu">
      <div class="ts item dropdown">
        <div class="text">games</div>
        <i class="dropdown icon"></i>
        <div class="menu">
          <a class="item" href="/games/r00m/">R00M</a>
          <a class="item" href="/games/dotdotdot/">DotDotDot</a>
          <a class="item" href="/games/supercold/">SUPERCOLD</a>
          <a class="item" href="/games/musquare/">MuSquare</a>
        </div>
      </div>
      ...
    </div>
  </div>
</nav>
```

My fix:
```css
.ts.dropdown.inverted .menu {
  background: #333333;
  box-shadow: 0px 1px 2px 0 #404040;
  border: 1px solid #404040;
}


.ts.dropdown.inverted .menu > .item {
  color: #fff !important;
}

.ts.dropdown.inverted .menu > .item:hover:not(:active):not(.active):not(.selected) {
  background: #292929 !important;
  color: #efefef !important;
}
```
