### ISSUE TITLE
在選單追加 Icon Item 讓單個項目可以成為僅有圖示而非整個使用圖示選單

### ISSUE THREAD

**Issue by t510599** [teacat/tocas#716]
ex: 在 menu 中 若一個 `.item` 中只有一個 `.icon`  他會看起來歪歪的

![default](https://user-images.githubusercontent.com/18533304/48303128-62525d00-e541-11e8-9d70-20bf7b817c1f.png)
如上圖 左: 未移除 右: 移除其 margin-right

```css
i.icon:only-child {
    margin-right: 0;
}
```
