### ISSUE TITLE
Pusher 捲動時頓感

### ISSUE THREAD

**Issue by t510599** [teacat/tocas#722]
在電腦上還好 但是在ipad算比較明顯 (Ex: TocasUI 官網)

看來是 `position: fixed` 所造成的 有什麼方法可以解決這個問題嗎（？）

**Comment by YamiOdymel** [comment]
這個問題應該是 Webkit 的問題 #570，修復的辦法是

```css
* {
  -webkit-overflow-scrolling: touch;
}
```

合併到 #570
