### ISSUE TITLE
TocasUI 與 code-prettify 一同使用

### ISSUE THREAD

**Issue by t510599** [teacat/tocas#735]
使用此套件庫 [google/code-prettify](https://github.com/google/code-prettify)

然後他就把行號全部炸掉了
![image](https://user-images.githubusercontent.com/18533304/51803511-da9f0380-2290-11e9-9aa3-d8e870a99723.png)

目前是先定義了自己的 counter 來解決
```css
pre.prettyprint ol.linenums:not(.ts) {
    counter-reset: code 0;
    margin-left: 0;
}

pre.prettyprint ol.linenums:not(.ts) > li::before {
    counter-increment: code;
    content: counter(code);
}
```
Code : [jsfiddle](https://jsfiddle.net/etojkfx7/)
