### ISSUE TITLE
.ts.one.cards 中的卡片放入表格 寬度異常

### ISSUE THREAD

**Issue by t510599** [teacat/tocas#737]
![image](https://user-images.githubusercontent.com/18533304/52208536-f8d1b880-28bb-11e9-8e0b-51ba4133af63.png)
有把 table 先用 div 包起來
```css
div.table.wrapper {
    overflow-x: auto;
    width: 100%
}
```

不過如果不是在 `.ts.one.cards` 裡面 直接放在 container 又會正常
code : [https://jsfiddle.net/poghs0k4/](https://jsfiddle.net/poghs0k4/)
