### ISSUE TITLE
增加 Floating Action Button（FAB）

### ISSUE THREAD

**Issue by Leon0824** [teacat/tocas#746]
Material Design 的 FAB 元件，希望也可以在 Tocas UI 有類似的元件可以使用。許願。

**Comment by YamiOdymel** [comment]
FAB 其實當初設計的時候不是沒有想過，但是在網頁上有個問題，就是 FAB 要「對齊」誰？

當網頁元素成為 `position: absolute` 的時候他在對齊某個父元件上就有點智障。

**Comment by Leon0824** [comment]
我以為 FAB 是固定在 viewport 的一個角落耶

像這樣

```css
#fab {
  position: fixed;
  right: 64px;
  bottom: 64px;
}
```
