### ISSUE TITLE
支援新的 `media query: prefers-color-scheme` 偏好色系

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#757]
**這是什麼**

新的媒體查詢語句 [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) 允許瀏覽器透過使用者色系偏好設置更改往站上的「亮色」與「暗色」主題。

```css
@media (prefers-color-scheme: dark) {
  div {
     color: white;
     background: black;
  }
}

@media (prefers-color-scheme: light) {
  div {
     color: black;
     background: white;
  }
}
```

**我們應該怎麼做**

讓 Tocas UI 支援亮色與暗色主題，並且能夠透過媒體查詢語句 `prefers-color-scheme` 在這兩個不同色系之間進行切換。

**相關討論**

[【twbs/bootstrap】Support for prefers-color-scheme media query](https://github.com/twbs/bootstrap/issues/27514)

**Comment by YamiOdymel** [comment]
我們可以只需要把新的 Tocas 3.0 顏色表全部改成 [CSS 變數](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)，如此一來就可以在不同色系時變更那些變數，而不需要替每個色系撰寫一次顏色定義。

```css
/** 
  * 變數
  */

@media (prefers-color-scheme: light) {
  :root {
    --pinkepieColor     : @color;
    --pinkepieBackground: @background;
  }
}

@media (prefers-color-scheme: dark) {
  :root {
    --pinkepieColor     : @darkColor;
    --pinkepieBackground: @darkBackground;
  }
}

/** 
  * 樣式定義
  */

.ts.pinkiepie.button {
   color     : var(--pinkepieColor);
   background: var(--pinkepieBackground);
}
```
