### ISSUE TITLE
[Feature Request] -is-stackable notice element

### ISSUE THREAD

**Issue by tobychui** [teacat/tocas#808]
I was wondering if tocas can add support for stackable notice element. Maybe with -is-stackable (for automatic stacking) or -is-stacked (for manual stacking)?

Current non-stackable notice
![圖片](https://user-images.githubusercontent.com/24617523/165028677-86256e0a-88a7-4097-ab16-6e3cbbc1cfb9.png)

Expected stackable notice
![圖片](https://user-images.githubusercontent.com/24617523/165028944-c5535cea-8640-4d7e-85c5-d4af096d6d34.png)

Thanks!

**Comment by YamiOdymel** [comment]
※ 給我自己的筆記

![image](https://user-images.githubusercontent.com/7308718/175951590-793a1d34-d67e-4f89-b586-cdc5e035e1d0.png)

![image](https://user-images.githubusercontent.com/7308718/175952156-7ff8af62-5843-4a01-9e82-03aadbf83e99.png)


折疊時更改 `.content` 與 `.title` 的樣式

```css
.ts-notice.is-dense {
    display: block;
}

.ts-notice.is-dense .title {
    display: inline-block;
    margin-right: 0.5rem;
    margin-top: 0.2rem;
}

.ts-notice.is-dense .content {
    display: inline;
}
```
