### ISSUE TITLE
table 響應式滑動

### ISSUE THREAD

**Issue by ChiaYuSu** [teacat/tocas#828]
想請教一下目前最新版本的 tocas-ui 有支援 table 的滑動嗎
表格太長，在手機版顯示會被吃欄位，謝謝

**Comment by YamiOdymel** [comment]
Table 一直都沒有辦法支援響應式設計，但你可以像 Bootstrap 那樣在外面用一個容器包裹他

```css
.ts-table-wrapper {
    display: block;
    width: 100%;
    overflow-x: auto;
    -webkit-overflow-scrolling: touch;
    -ms-overflow-style: -ms-autohiding-scrollbar;
}
```

```html
<div class="ts-table-wrapper">
    <table class="ts-table"> ... </table>
</div>
```

當表格太長，就能夠在 `.ts-table-wrapper` 裡面捲動他。
