### ISSUE TITLE
透過全新 Container Query 修正 ts-control 的寬度

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tocas#845]
[CSS Container Queries - CSS & Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries)

簡單說就是原本使用不可靠的 Media Query 來做螢幕裝置大小寬度的斷點，現在可以改成基於元素父容器的寬度來做斷點了。

原本是這樣

![image](https://user-images.githubusercontent.com/7308718/192164465-d6c35995-1c6c-4726-b708-d268ea579971.png)

即便螢幕很寬，如果父容器太小就可以自動變成這樣

![image](https://user-images.githubusercontent.com/7308718/192164469-3a1f91c8-d749-4b0b-8577-1f5dae8c31c3.png)

基本的 Container Query 長這樣：

```css
@container (max-width: 660px) {
    .ts-control {
        grid-template-columns: 1fr;
        gap: 0.5rem;
    }
    .ts-control .label {
        text-align: left;
        line-height: 1;
    }
    .ts-control .content {
        width: 100%;
        max-width: 100%;
    }
}
```

但看起來所有父容器都必須指定 `container-type`，其子元素的 Container Query 才會生效，

所以所有的 `ts` 元件可能預設都要指定 `container-type: inline-size;` 了。
