### ISSUE TITLE
"ts-image is-circular" 無法直接改動子物件嗎？

### ISSUE THREAD

**Issue by Alpaca0x0** [teacat/tocas#877]
😗 我使用 `cropper.js` 裁切圖片，並且將裁切框比例設置為 1：1，然後在 preview 的 div 設置 overflow: hidden，這麼一來便可以在裁切時，顯示一個正方形的預覽圖片。

🥴 然後我在該 div 中使用 class `ts-image is-circular`，我預期的效果是，該 class 會將該正方形預覽圖顯示為正圓形，但它卻無視了 div，轉而直接將整張預覽圖(div 中的 img)拉伸成橢圓，然後才被 preview div 裁切成正方形。

( ･᷄ὢ･᷅ )
也就是說，變成一個正方形的容器，裡面有橢圓型的圖片。

😕 還是這是我的食用方式錯誤嗎？
(p.s. 在先前的版本(v2)可以如預期的執行)

---

不太清楚，但感覺是先前的設計是直接對子物件進行變形

![image](https://user-images.githubusercontent.com/58300460/209204287-7ff676ac-28ea-4c68-8dc5-61e05fcfc49e.png)

而當前的版本則是直接指定 img？

![image](https://user-images.githubusercontent.com/58300460/209204572-28dc61cd-33a5-4318-9704-0f2660e95caa.png)

**Comment by YamiOdymel** [comment]
Image 的用法其實到現在還是讓我有點難以設計，因為有時候樣式要套用在容器上，有時候樣式又該套用在 `img` 上。

以你的用法來說，這個 `border-radius` 的樣式應該要套用給誰？

(1) `.ts-image` 容器還有 (2) `.ts-image > *` 裡面的所有子物件嗎？

**Comment by Alpaca0x0** [comment]
如果是套用在 img 上，那麼圖片必須是正方形；但若是套用在容器上，則只需容器是正方形。

um... 在我的 case 中，由於 img 是被自動生成的(cropper.js)，我不太想要從外部另外改變它生成的 DOM，而是期望圓形的效果是作用在外面的容器上，相當於遮照這樣，而非直接對圖片進行更動。

(抱歉，對前端不太懂，請問您提到的容器跟 img 本身都有需要被套用這個圓形效果的時侯，想請問什麼時候必須要作用在 img 上@@？謝謝。

**Comment by YamiOdymel** [comment]
讓我再想想 🤔

舉例來說：有時候 `<div class="ts-image">` 這個容器可能會因為某些原因而被「**拉伸**」，

這個時候他的「正圓形」是套用在《容器》上，就會變得很奇怪（簡單說就是像橢圓形啦），

所以我當初才決定要把 `border-radius` 設定給圖片，因為圖片才是主體。

---

如果新增一個 `.ts-image.is-circular.is-masked` 的樣式，讓圓角套用在容器而不是圖片呢？

```css
.ts-image.is-circular img {
    border-radius: 100rem;
}

/** .is-masked 會讓 border-radius 套用在容器，而不是圖片 */
.ts-image.is-circular.is-masked {
    border-radius: 100rem !important;
}
.ts-image.is-circular.is-masked img {
    border-radius: initial !important;
}

```
