### ISSUE TITLE
步驟指示器扁掉

### ISSUE THREAD

**Issue by hqn21** [teacat/tocas#883]
如題
步驟指示器在超過一行的時候會扁掉
似乎是沒有加is-completed或is-active的才會出現這個問題（純item）

![655BC7E7-0101-4F1D-B800-C67F5CBDA5F0](https://user-images.githubusercontent.com/23024789/209658545-0289f233-3297-4a6f-86b5-000d1d6e0ee4.jpeg)

**Comment by YamiOdymel** [comment]
暫時修正用的 CSS，主要是 Flexbox 的文字區塊會太寬而把數字擠扁

```css
.ts-procedure .item .indicator {
    min-width: 2rem;
    margin-top: -0.05rem;
}

.ts-procedure .item .content {
    align-items: flex-start;
}
```

大致上就可以修復

![sshot-2022-12-27-8](https://user-images.githubusercontent.com/7308718/209658934-9770a3d8-7711-40fe-8262-d0d870fd543b.png)

但因為這個臨時修正設置了 `min-width` 所以會影響到其他樣式，到時候要研究怎麼設計

![image](https://user-images.githubusercontent.com/7308718/209658896-078994b6-ed83-4973-b7c9-89293d6d2df4.png)
