### ISSUE TITLE
在 Firefox 瀏覽器中，`ts-control` `is-stacked` 導致 label 文字被裁剪

### ISSUE THREAD

**Issue by Alpaca0x0** [teacat/tocas#925]
### Infos

OS：Ubuntu 20.04.6 LTS
Browser：Firefox 115.0.2 (64-bits)

---

### Description

這是我的 code：

```html
<div class="ts-header is-center-aligned is-large">分類</div>
<div class="ts-text is-center-aligned is-description">
    調整分類後會自動重新加載商品列表
</div>

<div class="ts-divider is-section"></div>

<div class="ts-control is-stacked">
    <div class="label">商品標題</div>
    <div class="content">
        <div class="ts-input">
            <input type="text">
        </div>
    </div>
</div>
```

但實際運作卻長的像是：

![image](https://github.com/teacat/tocas/assets/58300460/3c593788-c33f-4297-9ca3-b58b7825ac32)

「*商品標題*」的部份被裁剪了，但 Chrome 卻沒有這個問題：

![image](https://github.com/teacat/tocas/assets/58300460/e0c7c5dd-8e46-4f03-bafb-a824137eec3e)

**Comment by YamiOdymel** [comment]
因為 `.label` 在超出一定長度時，會透過 `文字...` 自動截斷，要達到這個條件就必須指定 `overflow: hidden`，但也因為這樣而隱藏了文字的上下部份。

```css
.ts-control.is-stacked .label {
    line-height: 1.4  !important;
}
```

應該能暫時修正這個問題，如果不行的話，再試試看：

```css
.ts-control.is-stacked .label {
    overflow: visible !important;
}
```

**Comment by Alpaca0x0** [comment]
加上這段後解決了，感謝 ⸜(* ॑꒳ ॑* )⸝

```css
.ts-control.is-stacked .label {
    line-height: 1.4  !important;
}
```
